htmlize desktop version
iviteb/mega-menu pull request #2
Opened 2022-06-10 15:38 UTC by RobertIviteb

2022-06-15 08:08 UTC, cristian-milea commented on graphql/schema.graphql
> +  menu(id: ID!): Menu @cacheControl(scope: SEGMENT, maxAge: SHORT) @withSegment
maxAge aș pune MEDIUM (dacă exista)

2022-06-20 12:01 UTC, RobertIviteb commented on graphql/schema.graphql
> +  menu(id: ID!): Menu @cacheControl(scope: SEGMENT, maxAge: SHORT) @withSegment
Da, este

2022-06-20 12:09 UTC, RobertIviteb commented on react/MegaMenu/wrapper.tsx
> +  initMenu()
Nu pot, trebuie sa ramana asa. Daca il pui intr un useEffect cu [], pe partea de server side nu vine. Cred ca e un delay la useEffect chiar daca este chemat la initializare cu [], si atunci nu vine in dom server side.

2022-06-20 14:17 UTC, cristian-milea commented on react/MegaMenu/wrapper.tsx
> +  initMenu()
poti sa incerti cu https://github.com/vtex-apps/render-runtime#canusedom ?

2022-06-20 14:34 UTC, cristian-milea requested changes

2022-06-20 15:29 UTC, closed without merging