Iviteb 5253 fork improve
iviteb/mega-menu pull request #37
Opened 2024-05-30 11:07 UTC by RobertIviteb

- Includes feature to upload banners and images
- Added feature to generate CSV based on the actual category tree
- Added SSR functionality

2024-05-31 09:46 UTC, claudiu-iviteb requested changes

2024-05-31 14:36 UTC, RobertIviteb commented on graphql/types/menu.graphql
> +  uploadedIcon: String
Nu schimb icon pt ca icon e deja folosit nativ de mega menu.

2024-05-31 14:40 UTC, RobertIviteb commented on graphql/types/menu.graphql
> +  uploadedIcon: String
Schimb numele la banner atunci

2024-06-03 09:52 UTC, claudiu-iviteb approved these changes

2024-07-10 14:09 UTC, merged