added modify menu by seller id
iviteb/mega-menu pull request #7
Opened 2022-07-22 11:04 UTC by RobertIviteb

2022-08-01 11:04 UTC, claudiu-iviteb requested changes

2022-08-01 11:04 UTC, claudiu-iviteb commented on react/FormComponent.tsx
> +                      errorMessage={messageName}
Ce este acest messageName? Si de ce este aici?

2022-08-01 11:04 UTC, claudiu-iviteb commented on manifest.json
> +      "name": "OMSViewer"
De ce ai adaugat aceasta permisiune? De ce ai adaugat toate permisiunile, defapt?

2022-08-02 11:41 UTC, RobertIviteb commented on manifest.json
> +      "name": "OMSViewer"
Astea sunt permisiuni de la o alta aplicatie care ia regionId din session, le am incercat pe toate pt ca eu nu puteam sa iau regionId din sesiune chiar si cand faceam exact ca in alte aplicatii. Nu am putut sa iau regionId din sesiune oricum.

2022-08-02 11:42 UTC, RobertIviteb commented on react/FormComponent.tsx
> +                      errorMessage={messageName}
L am scos

2022-08-02 12:02 UTC, claudiu-iviteb approved these changes

2022-08-08 09:31 UTC, merged